---
title: "Bycatch Paper"
author: "Natasha Besseling"
date: "2023-06-06"
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: inline
---


```{r message=FALSE, warning=FALSE, include=FALSE}
#load packages
library(janitor)
library(fuzzySim)
library(ggthemes)
library(dendextend)
library(vegan)
library(tidyverse)
library(lubridate)
library(maptools)
library(maps)
library(mapdata)
library(wesanderson)
library(RColorBrewer)
library(sp)
library(gridExtra)
library(ggsn)  # north2() scalebar()
library(rworldmap) 
library(ggrepel)
library(plotrix)
library(ggdendro)
library(DBI)
library(RPostgres)
library(here)
library(gt)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
#load functions
## Normalise data
normalise <- function(dat, values, id, join) {
  
  test <- dat %>%
    group_by({{id}}) %>%
    summarise(total = sum({{values}}))
  
  test1 <-  dat %>%
    left_join(test, by = {{join}})
  
  test2 <- test1 %>%
    mutate(norm = {{values}} /total)%>%
    select(-total)
}
## pairwise tests for permanova
pairwise.adonis <- function(x,factors, sim.function = 'vegdist', sim.method = 'bray', p.adjust.m ='bonferroni')
{
  library(vegan)
  
  co = combn(unique(as.character(factors)),2)
  pairs = c()
  F.Model =c()
  R2 = c()
  p.value = c()
  
  
  for(elem in 1:ncol(co)){
    if(sim.function == 'daisy'){
      library(cluster); x1 = daisy(x[factors %in% c(co[1,elem],co[2,elem]),],metric=sim.method)
    } else{x1 = vegdist(x[factors %in% c(co[1,elem],co[2,elem]),],method=sim.method)}
    
    ad = adonis(x1 ~ factors[factors %in% c(co[1,elem],co[2,elem])] );
    pairs = c(pairs,paste(co[1,elem],'vs',co[2,elem]));
    F.Model =c(F.Model,ad$aov.tab[1,4]);
    R2 = c(R2,ad$aov.tab[1,5]);
    p.value = c(p.value,ad$aov.tab[1,6])
  }
  p.adjusted = p.adjust(p.value,method=p.adjust.m)
  sig = c(rep('',length(p.adjusted)))
  sig[p.adjusted <= 0.05] <-'.'
  sig[p.adjusted <= 0.01] <-'*'
  sig[p.adjusted <= 0.001] <-'**'
  sig[p.adjusted <= 0.0001] <-'***'
  
  pairw.res = data.frame(pairs,F.Model,R2,p.value,p.adjusted,sig)
  print("Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1")
  return(pairw.res)
  
} 

```



```{r include=FALSE}
#load the data
#connect to the sql database
con <- dbConnect(RPostgres::Postgres(),
                 dbname = "masters_paper",
                 port = 5432,
                 user = "postgres",
                 password = "A.inodorus")

drags <- dbReadTable(con, "drags" )
landings <- dbReadTable(con, "landings" )
drag_catches <- dbReadTable(con, "drag_catches")
landings_catches <- dbReadTable(con, "landings_catches" )


#close connection to the database
dbDisconnect(con)
```




```{r echo=FALSE, message=FALSE, warning=FALSE}
#calculate the bycatch composition by weight
# total number of species

test <- landings_catches %>%
  distinct(species_code)

#49

##total catch composition

test <- landings_catches%>%
  group_by(species_code)%>%
  summarise(mass = sum(nominal_mass, na.rm = T))%>%
  mutate(proportion = mass/sum(mass))

#hake = 57.4
#sole = 4.2


## Top species

species <- landings_catches %>%
  mutate(nominal_mass= nominal_mass/1000)%>%
  group_by(species_code, scientific_name, docking_date_yy)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  pivot_wider(names_from = docking_date_yy, values_from = nominal_mass)%>%
  mutate_all(~replace_na(.,0))%>%
  pivot_longer(cols = 3:32, names_to = "docking_date_yy", values_to = "nominal_mass")%>%
  group_by(species_code, scientific_name)%>%
  summarise(nominal_mass=sum(nominal_mass)/30)


species <- species[order(-species$nominal_mass),]

species <- species %>%
  ungroup() %>% 
  mutate(cumsum = round(cumsum(nominal_mass))) %>%
  mutate(Percent_of_total = round(cumsum/sum(nominal_mass)*100, digits= 2))%>%
#  mutate(percentage_landings= round(nominal_mass/sum(nominal_mass)*100, digits= 2))%>%
  mutate(nominal_mass= round(nominal_mass))


topspp <- species %>%
  filter(Percent_of_total <= 98)%>%
  select(species_code)

species[1:14,] %>% 
  select(-species_code) %>% 
  gt() %>% 
  tab_header(title = "Landed catch composition") %>% 
   cols_label(
    scientific_name = html("**Scientific <br> Name**"),
    nominal_mass = html("**Nominal <br> Mass**"),
    cumsum = html("**Cumulative <br> Sum**"),
    Percent_of_total = html("**Cumulative <br> Percentage**"),
    .fn = md) %>% 
  cols_align(align = c("center"),
             columns = c(nominal_mass, cumsum, Percent_of_total))
```


Cluster analysis of vessels 

```{r echo=FALSE, message=FALSE, warning=FALSE}

#determine if the vessel is a hake or sole directed vessel
target_code <- drags %>%
  count(vessel_number, target_species_code)%>%
  normalise(n, vessel_number, "vessel_number")%>%
  filter(!norm<0.5)%>%
  mutate(target_code = if_else(norm>0.5 & 
                                 target_species_code == "HAKE", 
                               "Hake",
                               if_else(norm>0.5 & 
                                         target_species_code == "ECSOLE", 
                                       "Sole", "both"), "both"))



####
#cluster
####

#sum the catch by vessel, and normalise and square root the catch comp per vessel
test <- landings_catches%>%
  right_join(topspp)%>%
  group_by(vessel_number,species_code)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  normalise(nominal_mass, vessel_number, "vessel_number")%>%
  mutate(norm = sqrt(norm))%>%
  ungroup()%>%
  select(vessel_number, norm, species_code)%>%
  pivot_wider(names_from = species_code, values_from = norm)%>%
  mutate_all(~replace_na(.,0))%>%
  ungroup()%>% 
  column_to_rownames(var = "vessel_number")

#write.csv(test, "simp.ves.csv", row.names = F)

#distance matrix
dm <- vegdist(test, method="bray", na.rm = T)

#cluster
cluster<- dm %>%
  hclust(method = "average")

#plot the cluster analysis in a dendrogram (try get the numbers the right way)
x <- cluster%>%
  as.dendrogram()%>% 
  dendextend::set("labels_cex", 0.8)%>%
  dendextend::set("branches_lwd", 2)%>%
  colour_branches(h = 0.25, groupLabels = T,
                  col = brewer.pal(2,"Paired"))

plot(x)
title(ylab = 'Dissimilarity', line = 2.5)
title(xlab = 'Vessels', line = 2)

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
#get the cluster groups into the catch comp dataframe
dend_list <- get_subdendrograms(x, 2)
labels <- lapply(dend_list, labels)
grp<- labels %>%
  plyr::ldply( rbind)%>%
  t()%>%
  as_tibble()%>%
  pivot_longer(cols= 1:2,names_to = "grp", values_drop_na = T )%>%
  column_to_rownames(var = "value")

ves.s <- test %>% 
  merge(grp, by = "row.names")%>% 
  mutate(Row.names = as.numeric(Row.names)) %>% 
  left_join(select(target_code, vessel_number, target_code), by = c("Row.names" = "vessel_number"))


#write.csv(ves.s, "simp.ves.csv", , row.names = F)

#### MDS

#distance matrix

dm <- vegdist(ves.s[2:15], method="bray", na.rm = T)

#Do MDS
mds <- metaMDS(dm, 
               k=3,
               try=15, trymax=20,
               autotransform = FALSE)         #if it doesn't converge increase k by 1. 


MDS_xy <- data.frame(mds$points)


ggplot(MDS_xy, aes(MDS1, MDS2, colour = ves.s$grp, shape = ves.s$target_code)) +
  geom_point(size = 5) + 
  theme(legend.title = element_text(size = 14, face = "bold"), 
        legend.text = element_text(size = 12, face = "bold"), 
        legend.position = "right", 
        axis.text.x = element_text(face = "bold",colour = "black", size = 12), 
        axis.text.y = element_text(face = "bold", size = 12, colour = "black"), 
        axis.title.y = element_text(face = "bold", size = 14, colour = "black"),
        axis.title.x = element_text(face = "bold", size = 14, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) + 
  labs(x = "MDS 1", y = "MDS 2", colour = "Cluster", shape = "Target Species") +
  scale_colour_brewer(palette = "Paired", aesthetics = "colour")


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#bar graph
grp1 <- grp %>%
  rownames_to_column(var = "vessel_number")

spp <- topspp %>%
  rownames_to_column(var = "id")%>%
  mutate(id = as.numeric(id))

landings_catches%>%
  mutate(vessel_number = as.character(vessel_number)) %>% 
  right_join(spp)%>%
  left_join(grp1)%>%
  group_by(grp, id, species_code)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  normalise(nominal_mass, grp, "grp")%>%
  mutate(norm = sqrt(norm))%>%
  ggplot(aes(reorder(species_code, id), norm, fill = grp))+
  geom_col()+
  facet_wrap(~grp)+
  theme(legend.title = element_blank(), 
        legend.position = "none",
        axis.text.x = element_text(face = "bold",colour = "black", size = 8, 
                                   angle = 90, vjust = 0.5, hjust=1), 
        axis.text.y = element_text(face = "bold", size = 8, colour = "black"), 
        axis.title.y = element_text( face = "bold", size = 12, colour = "black"),
        axis.title.y.right = element_text( face = "bold", size = 12, colour = "blue"),
        axis.title.x = element_text(face = "bold", size = 12, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) +
  labs(x = "Species code", y = "Proportion")+
  scale_fill_brewer(palette = "Paired", aesthetics = "fill")


```


cluster analysis of year

```{r echo=FALSE, message=FALSE, warning=FALSE}
####
#cluster
####

test <- landings_catches%>%
  right_join(topspp)%>%
  group_by(docking_date_yy, species_code)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  normalise(nominal_mass, docking_date_yy, "docking_date_yy")%>%
  mutate(norm = sqrt(norm))%>%
  select(docking_date_yy, norm, species_code)%>%
  pivot_wider(names_from = species_code, values_from = norm)%>%
  mutate_all(~replace_na(.,0))%>%
  ungroup()%>%
  column_to_rownames(var = "docking_date_yy")


#distance matrix

dm <- vegdist(test, method="bray", na.rm = T)

#cluster

cluster<- dm %>%
  hclust(method = "average")


x <- cluster%>%
  as.dendrogram(xlab = "Years", ylab = "Dissimilarity")%>% 
  dendextend::set("labels_cex", 0.8)%>%
  dendextend::set("branches_lwd", 2)%>%
  colour_branches(h = 0.15, groupLabels = T,
                  col = brewer.pal(3, "Dark2"))
plot(x)
title(ylab = 'Dissimilarity', line = 2.5)
title(xlab = 'Years', line = 2)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

dend_list <- get_subdendrograms(x, 2)
labels <- lapply(dend_list, labels)
grp<- labels %>%
  plyr::ldply( rbind)%>%
  t()%>%
  as_tibble()%>%
  rename(Y1 = V1,
         Y2 = V2)%>%
  pivot_longer(cols= 1:2,names_to = "grp", values_drop_na = T )%>%
  column_to_rownames(var = "value")


year.s <- merge(test, grp, by = "row.names")



#### MDS

#distance matrix

dm <- vegdist(year.s[2:15], method="bray", na.rm = T)

#Do MDS
mds <- metaMDS(dm, 
               k=3,
               try=15, trymax=20,
               autotransform = FALSE)         #if it doesn't converge increase k by 1. 


MDS_xy <- data.frame(mds$points)

test <- year.s %>%
  mutate(path = "a")

ggplot(MDS_xy, aes(MDS1, MDS2, colour = test$grp)) +
  geom_path(group= test$path)+
  geom_text(label= test$Row.names, nudge_x = 0.015)+
  #  geom_line(group= test$grp)+
  geom_point(size = 2) + 
  theme(legend.title = element_text(size = 14, face = "bold"), 
        legend.text = element_text(size = 12, face = "bold"), 
        legend.position = "right", 
        axis.text.x = element_text(face = "bold",colour = "black", size = 12), 
        axis.text.y = element_text(face = "bold", size = 12, colour = "black"), 
        axis.title.y = element_text(face = "bold", size = 14, colour = "black"),
        axis.title.x = element_text(face = "bold", size = 14, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) + 
  labs(x = "MDS 1", y = "MDS 2", colour = "group") +
  scale_fill_brewer(palette = "Dark2", aesthetics = "colour")

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

####
#graphs
####
grp <- grp %>%
  rownames_to_column(var = "docking_date_yy")

spp <- topspp%>%
  rownames_to_column(var = "id")%>%
  mutate(id = as.numeric(id))

landings_catches%>%
  right_join(spp)%>%
  mutate(docking_date_yy = as.character(docking_date_yy)) %>% 
  right_join(grp)%>%
  group_by(grp, id, species_code)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  normalise(nominal_mass,grp, "grp")%>%
  mutate(norm = sqrt(norm))%>%
  ggplot(aes(reorder(species_code, id), norm, fill = grp))+
  geom_col()+
  facet_wrap(~grp)+
  theme(legend.title = element_blank(), 
        legend.position = "none",
        axis.text.x = element_text(face = "bold",colour = "black", size = 8, 
                                   angle = 90, vjust = 0.5, hjust=1), 
        axis.text.y = element_text(face = "bold", size = 8, colour = "black"), 
        axis.title.y = element_text( face = "bold", size = 12, colour = "black"),
        axis.title.y.right = element_text( face = "bold", size = 12, colour = "blue"),
        axis.title.x = element_text(face = "bold", size = 12, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) +
  labs(x = "Species code", y = "Proportion")+
  scale_fill_brewer(palette = "Dark2", aesthetics = "fill")

```


Cluster analysis of months
```{r echo=FALSE, message=FALSE, warning=FALSE}
####
#cluster
####

month<- landings_catches %>%
  separate(land_id, c(NA,NA,NA,"docking_date"), sep = ",", remove = F )%>%
  mutate(docking_date = as.Date(docking_date)) %>%               
  mutate(month = months(docking_date)) %>% 
  mutate(season = quarter(docking_date)) %>% 
  mutate(season = if_else(season == 1, "Summer", 
                          if_else(season == 2, "Autumn", 
                                  if_else(season == 3, "Winter", "Spring"))))


test <- month%>%
  right_join(topspp)%>%
  group_by(month,season, species_code)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  normalise(nominal_mass, month, "month")%>%
  mutate(norm = sqrt(norm))%>%
  ungroup()%>%
  select(month, norm, species_code)%>%
  pivot_wider(names_from = species_code, values_from = norm)%>%
  mutate_all(~replace_na(.,0))%>%
  ungroup()%>%
  column_to_rownames(var = "month")

#write.csv(test, "simp.season.csv", row.names = F)

#distance matrix

dm <- vegdist(test, method="bray", na.rm = T)

#cluster

cluster<- dm %>%
  hclust(method = "average")

x <- cluster%>%
  as.dendrogram()%>% 
  dendextend::set("labels_cex", 0.8)%>%
  dendextend::set("branches_lwd", 2)%>%
  colour_branches(h = 0.06, groupLabels = T,
                  col = brewer.pal(3,"Accent"))
plot(x)
title(ylab = 'Dissimilarity', line = 2.5)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
dend_list <- get_subdendrograms(x, 3)
labels <- lapply(dend_list, labels)
grp<- labels %>%
  plyr::ldply( rbind)%>%
  t()%>%
  as_tibble()%>%
  rename(S1 = V1,
         S2 = V2,
         S3 = V3)%>%
  pivot_longer(cols= 1:3,names_to = "grp", values_drop_na = T )%>%
  column_to_rownames(var = "value")

sea.s <- test %>% 
  merge(grp, by = "row.names") %>% 
  left_join(select(month, month, season), by = c("Row.names" = "month")) %>% 
  distinct()
#write.csv(sea.s, "simp.season.csv", row.names = F)

#### MDS

#distance matrix

dm <- vegdist(sea.s[2:15], method="bray", na.rm = T)

#Do MDS
mds <- metaMDS(dm, 
               k=3,
               try=15, trymax=20,
               autotransform = FALSE)         #if it doesn't converge increase k by 1. 


MDS_xy <- data.frame(mds$points)


ggplot(MDS_xy, aes(MDS1, MDS2, colour = sea.s$grp, shape = sea.s$season)) +
  geom_point(size = 6) + 
  theme(legend.title = element_text(size = 14, face = "bold"), 
        legend.text = element_text(size = 12, face = "bold"), 
        legend.position = "right", 
        axis.text.x = element_text(face = "bold",colour = "black", size = 12), 
        axis.text.y = element_text(face = "bold", size = 12, colour = "black"), 
        axis.title.y = element_text(face = "bold", size = 14, colour = "black"),
        axis.title.x = element_text(face = "bold", size = 14, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) + 
  labs(x = "MDS 1", y = "MDS 2", colour = "group", shape = "season") +
  scale_fill_brewer(palette = "Accent", aesthetics = "colour")

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

####
#graphs
####

season<- grp %>%
  rownames_to_column(var = "month")
  

month%>%
  right_join(spp)%>%
  right_join(season)%>%
  group_by(grp, id, species_code)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  normalise(nominal_mass,grp, "grp")%>%
  mutate(norm = sqrt(norm))%>%
  ggplot(aes(reorder(species_code, id), fill = grp, norm))+
  geom_col(position = "dodge")+
  ylim(0,NA)+
  facet_wrap(~grp)+
  theme(legend.title = element_blank(), 
        axis.text.x = element_text(face = "bold",colour = "black", size = 8, 
                                   angle = 90, vjust = 0.5, hjust=1), 
        axis.text.y = element_text(face = "bold", size = 8, colour = "black"), 
        axis.title.y = element_text( face = "bold", size = 12, colour = "black"),
        axis.title.y.right = element_text( face = "bold", size = 12, colour = "blue"),
        axis.title.x = element_text(face = "bold", size = 12, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) +
  labs(x = "Species code", y = "Proportion")+
  scale_fill_brewer(palette = "Accent", aesthetics = "fill")

```

cluster analysis of area

```{r echo=FALSE, message=FALSE, warning=FALSE}
#area
#get world map
world <- getMap(resolution = "low")

#get country I want
RSA <- c("South Africa")

# Call the vector in `borders()`
world_saf <- world[world@data$ADMIN %in% RSA, ]

grid_code_south <- read.csv(here("data/grid_code_south.csv"))

grids.south <- grid_code_south%>%
  mutate(mid_lat = (lat_N+lat_S)/2)%>%
  mutate(mid_long = (long_W+long_E)/2)%>%
  select(grid, mid_lat, mid_long)%>%
  mutate(grid_code = as.character(grid), .keep = "unused")


#spp composition of area
#grid_code
####
#cluster
####

count <- drags %>%
  count(grid_code)%>%
  filter(!is.na(grid_code))%>%
  select(grid_code)

grid <- drag_catches%>%
  left_join(select(drags,drag_id, depth, grid_code))%>%
  left_join(count)%>%
  right_join(topspp)%>%
  group_by(grid_code, species_code)%>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T))%>%
  normalise(nominal_mass, grid_code, "grid_code")%>%
  mutate(norm = sqrt(norm))%>%
  select(grid_code, norm, species_code)%>%
  pivot_wider(names_from = species_code, values_from = norm)%>%
  mutate_all(~replace_na(.,0))%>%
  ungroup()%>%
  column_to_rownames(var = "grid_code")

#write.csv(grid, "simp.area.csv", row.names = F)


#distance matrix

dm <- vegdist(grid, method="bray", na.rm = T)

#cluster

cluster<- dm %>%
  hclust(method = "average")

x <- cluster%>%
  as.dendrogram()%>% 
  dendextend::set("labels_cex", 0.7)%>%
  dendextend::set("branches_lwd", 2)%>%
  colour_branches(h = 0.15, groupLabels = TRUE,
                  col = brewer.pal(6,"Paired"))
plot(x)
title(ylab = 'Dissimilarity', line = 2.5)
title(xlab = 'Grid cells', line = 2)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

dend_list <- get_subdendrograms(x,6)
labels <- lapply(dend_list, labels)
grp<- labels %>%
  plyr::ldply( rbind)%>%
  t()%>%
  as_tibble()%>%
  rename(G1 = V1,
         G2 = V2,
         G3 = V3,
         G4 = V4,
         G5 = V5,
         G6 = V6)%>%
  pivot_longer(cols= 1:6,names_to = "grp", values_drop_na = T )%>%
  column_to_rownames(var = "value")



grid.s <- grid %>%
  merge( grp, by = "row.names")

#write.csv(grid.s, "simp.area.csv", row.names = F)
#### MDS

#distance matrix


dm <- vegdist(grid.s[2:15], method="bray", na.rm = T)

#Do MDS
mds <- metaMDS(dm, 
               k=3,
               try=15, trymax=20,
               autotransform = FALSE)         #if it doesn't converge increase k by 1. 


MDS_xy <- data.frame(mds$points)


ggplot(MDS_xy, aes(MDS1, MDS2, colour = grid.s$grp, shape =grid.s$grp )) +
  geom_point(size = 6)+
  #  geom_text(label = grid.s$Row.names)+
  theme(legend.title = element_text(size = 14, face = "bold"), 
        legend.text = element_text(size = 12, face = "bold"), 
        legend.position = "right", 
        axis.text.x = element_text(face = "bold",colour = "black", size = 12), 
        axis.text.y = element_text(face = "bold", size = 12, colour = "black"), 
        axis.title.y = element_text(face = "bold", size = 14, colour = "black"),
        axis.title.x = element_text(face = "bold", size = 14, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) + 
  labs(x = "MDS 1", y = "MDS 2", colour = "group", shape = "group") +
  scale_fill_brewer(palette = "Paired", aesthetics = "colour", 
                    breaks=c('G1', 'G2','G3','G4','G5',
                             'G6','G7','G8', "G9"))


```

```{r echo=FALSE, message=FALSE, warning=FALSE}

#map
grids.map <- read.csv(here("data/map_grid.csv"))

grid.s <- grid.s %>%
  left_join(grids.south, by = c("Row.names"="grid_code"))%>%
  select(c(Row.names, grp, mid_lat, mid_long))

ggplot() +
  geom_polygon(data = world_saf, 
               aes(x=long, y=lat, group=group), 
               fill="grey", 
               colour="black") +
  coord_quickmap() +
  coord_sf(xlim = c(18.00, 28.00), ylim = c(-32.00, -37.00), expand = T) +
    geom_segment(data = grids.map, aes(x = vlong_start, 
                                       y= vlat_start, 
                                       xend = vlong_end,
                                       yend = vlat_end) )+
    geom_segment(data = grids.map, aes(x = hlong_start, 
                                       y= hlat_start, 
                                       xend = hlong_end,
                                       yend = hlat_end) ) +
  geom_point(data=grid.s, aes(mid_long, mid_lat,  alpha=I(0.7), colour = grp),
             size = 5, shape = 15) +
  labs(x="", y="", colour = "Groups") +
  scale_fill_brewer(palette = "Paired", aesthetics = "colour", 
                    breaks=c('G1', 'G2','G3','G4','G5',
                             'G6','G7','G8','G9','G10',
                             'G11','G12'))+
  theme_bw()

#  north(world_saf, location = "topmright", symbol = 15) +
#  scale_fill_continuous(low = "#fff7ec", high = "#7F0000")+
#  scalebar(world_saf, dist = 4, dist_unit = "m",
#           transform = FALSE, model = "WGS84") +
#  blank() +
#  scale_fill_continuous(low = "#fff7ec", high = "#7F0000")

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
spp <- topspp %>%
  rownames_to_column(var = "id")%>%
  mutate(id = as.numeric(id))

grp <- grp %>%
  rownames_to_column(var = "grid_code")

test <- drag_catches%>%
  left_join(select(drags, drag_id, grid_code)) %>% 
  mutate(grid_code = as.character(grid_code)) %>% 
  right_join(spp) %>%
  left_join(grp) %>%
  group_by(grp, id, species_code) %>%
  summarise(nominal_mass = sum(nominal_mass, na.rm = T)) %>%
  normalise(nominal_mass,grp, "grp") %>%
  mutate(norm = sqrt(norm))

test%>%
  ggplot(aes(reorder(species_code, id), norm, fill = grp))+
  geom_col(position = "dodge")+
  facet_wrap(~grp, scales = "free_y")+
  theme(legend.title = element_blank(), 
        legend.text = element_blank(), 
        legend.position = "none",
        axis.text.x = element_text(face = "bold",colour = "black", size = 8,
                                   angle = 90, vjust = 0.5, hjust=1), 
        axis.text.y = element_text(face = "bold", size = 8, colour = "black"), 
        axis.title.y = element_text( face = "bold", size = 12, colour = "black"),
        axis.title.y.right = element_text( face = "bold", size = 12, colour = "blue"),
        axis.title.x = element_text(face = "bold", size = 12, colour = "black"),
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.key=element_blank()) +
  labs(x = "Species", y = "Proportion")+
  scale_fill_brewer(palette = "Paired", aesthetics = "fill")

```

Bycatch composition models
```{r}
#permanova model 1
## PERMANOVA model 1 - year, season, vessel - trip data

test <- landings_catches%>%
  separate(land_id, c(NA,NA,NA,"docking_date"), sep = ",", remove = F )%>%
  mutate(docking_date = as.Date(docking_date)) %>%               
#  mutate(month = months(docking_date)) %>% 
  mutate(season = quarter(docking_date)) %>% 
  mutate(season = if_else(season == 1, "Summer", 
                          if_else(season == 2, "Autumn", 
                                  if_else(season == 3, "Winter", "Spring")))) %>% 
  right_join(topspp)%>%
  normalise(nominal_mass, land_id, "land_id")%>%
  mutate(norm = sqrt(norm))%>%
  select(-c(nominal_mass, scientific_name))%>% 
  pivot_wider(names_from = species_code, values_from = norm)%>%
  mutate(season = as.character(season))%>%
  mutate_all(~replace_na(.,0))



#random sample
test.1 <- test %>%
  slice_sample(prop = 0.35)

#distance matrix

dm <- vegdist(test.1[6:19], method="bray", na.rm = T)


#Do a PERMANOVA

permanova <- adonis2(dm~ docking_date_yy*season*vessel_number, data = test.1[3:5])
permanova



# do dispersion test to see if centroids or dispersions differ 
year <- betadisper(dm, test.1$docking_date_yy, type = "centroid")

vessel <- betadisper(dm, test.1$vessel_number, type = "centroid")

season <- betadisper(dm, test.1$season, type = "centroid")


# do anova of dispersions
anova.year<- anova(year)
anova.year

anova.ves <-  anova(vessel)
anova.ves

anova.sea <- anova(season)
anova.sea

# plot the dispersions

plot(year, hull=FALSE, ellipse=TRUE)
plot(vessel, hull=FALSE, ellipse=TRUE)
plot(season, hull=FALSE, ellipse=TRUE)


```

```{r}
## area permanova - trawl data

###make data

drag.effort <- drags.1%>%
  mutate(trawl_length_hh = if_else(!between(trawl_length_hh, 0.5, 9),
                                   3.5, trawl_length_hh))%>%
  group_by(drag_ID)%>%
  summarise(trawl_length_hh = sum(trawl_length_hh, na.rm = T))

area <- drag.catches.a %>%
  filter(vessel_number %in% c('96', '93', '191', '244', "225"))%>%
  filter(grid_code %in% c('512', '525','524', '514', '513', '523', '526', '554', '540', '555'))%>%
  filter(docking_date_yy %in% c('2004', '2006'))




## PERMANOVA

test <- area%>%
  filter(nominal_mass != 0)%>%
  right_join(topspp)%>%
  normalise(nominal_mass, drag_ID, "drag_ID")%>%
  mutate(norm = sqrt(norm))%>%
  mutate(season = as.character(season))%>%
  select(-c(nominal_mass, company_number))%>%
  pivot_wider(names_from = species_code, values_from = norm)%>%
  mutate_all(~replace_na(.,0))

spp <- test %>%
  select(-c(docking_date_yy, season, vessel_number, grid_code))

env <- test %>%
  select(c(drag_ID,docking_date_yy, season, vessel_number, grid_code))


write.csv(spp, "area.cluster.spp.csv", row.names = F)
write.csv(env, "area.cluster.env.csv", row.names = F)


#random sample
test.1 <- test %>%
  slice_sample(prop = 0.25)

spp <- test.1 %>%
  select(-c(docking_date_yy, season, vessel_number, grid_code))

env <- test.1 %>%
  select(c(drag_ID,docking_date_yy, season, vessel_number, grid_code))


write.csv(spp, "area.cluster.spp.csv", row.names = F)
write.csv(env, "area.cluster.env.csv", row.names = F)

#distance matrix

dm <- vegdist(test.1[6:18], method="bray", na.rm = T)


#Do a PERMANOVA

adonis(dm~ docking_date_yy*season*grid_code*vessel_number, data = test.1[1:5])



# do dispersion test to see if centroids or dispersions differ 
year <- betadisper(dm, test.1$docking_date_yy, type = "centroid")

vessel <- betadisper(dm, test.1$vessel_number, type = "centroid")

grid <- betadisper(dm, test.1$grid_code, type = "centroid")


# do anova of dispersions
anova.year<- anova(year)
anova.year

anova.ves <-  anova(vessel)
anova.ves

anova.grid <- anova(grid)
anova.grid

# plot the dispersions

plot(year, hull=FALSE, ellipse=TRUE)
plot(vessel, hull=FALSE, ellipse=TRUE)
plot(grid, hull=FALSE, ellipse=TRUE)


```



